# 服务配置
server:
  port: 5800  # 监听端口

# 云平台配置
api:
  base_url: https://cloud.drea.cc  # 云平台地址

# 认证配置
auth:
  username: your_username  # 云平台用户名
  password: your_password  # 云平台密码

# 输入配置
input:
  is_enable: true  # 是否启用输入，调试动作的时候可以关闭
